Revert "build(deps): bump logstash-logback-encoder from 7.3 to 7.4" (#1053)
This reverts commit c1b49e5bffe9d5c1d0a7e929eacf575474735d1c.

7.4 version dropped support for logback 1.2
https://github.com/logfellow/logstash-logback-encoder/releases/tag/logstash-logback-encoder-7.4

it causes a NoSuchMethodError: 'java.time.Instant ch.qos.logback.classic.spi.ILoggingEvent.getInstant()'
when using build=routine in camel-k